### ISSUE TITLE
Merge EDM4hep-utils into EDM4hep

### ISSUE THREAD

**Issue by andresailer** [key4hep/EDM4hep-utils#2]
As discussed in EDM4hep meeting on June 29.
Suppress this package (move the PR to EDM4hep).

**Comment by tmadlener** [comment]
Opened key4hep/EDM4hep#120 for moving the "contents"

**Comment by tmadlener** [comment]
I will archive this repository for now and delete it later just for the unlikely case someone already depends on this.
